#!/bin/bash -e
#
# To enable:
#   git config --local core.hooksPath githooks

cat <<EOF
 #####   #    #  #    #  #    #     #    #    #   ####
 #    #  #    #  ##   #  ##   #     #    ##   #  #    #
 #    #  #    #  # #  #  # #  #     #    # #  #  #
 #####   #    #  #  # #  #  # #     #    #  # #  #  ###
 #   #   #    #  #   ##  #   ##     #    #   ##  #    #
 #    #   ####   #    #  #    #     #    #    #   ####


 #          #    #    #   #####   ####
 #          #    ##   #     #    #
 #          #    # #  #     #     ####
 #          #    #  # #     #         #   ###     ###
 #          #    #   ##     #    #    #   ###     ###
 ######     #    #    #     #     ####    ###     ###
EOF

for script in csv-audit.py python/*.py; do
    flake8 "$script"
done

for script in stk-*.bash; do
    [[ $script = 'shell-utils.bash' ]] && continue
    shellcheck -x "$script" shell-utils.bash
done

for json in $(find . -name '*.json'); do
    jq . "$json" > /dev/null
done

exit 0
